version: "3"
services:
  database:
    build:
      context: ./db
      dockerfile: Dockerfile
      target: database
    container_name: todo_postgres
    ports:
      - 5432:5432
    volumes:
      - pgdate:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
volumes:
  pgdate:
